// Generated by CoffeeScript 1.10.0
(function() {
  (function($) {
    $.widget('ui.sendFilesProxy', {
      send: function(options) {
        var file, reader;
        if (!options.counter) {
          options.counter = 0;
        }
        this.files = document.getElementById(this.element.attr('id')).files;
        if (options.counter < this.files.length) {
          reader = new FileReader();
          file = this.files[options.counter];
          reader.onload = (function(_this) {
            return function(event) {
              return _this._send_file(new FormData(), event.target.result, file, options);
            };
          })(this);
          reader.readAsDataURL(file);
          return options.counter++;
        } else {
          this.element.val('');
          if (options.complete) {
            return options.complete();
          }
        }
      },
      _send_file: function(data, result, file, options) {
        if (!options.extensions || $.inArray(name.replace(/^.*\./, '').toLowerCase(), options.extensions)) {
          return this._post_data(this._set_params(data, file, options), options, (function(_this) {
            return function(response) {
              if (options.progress) {
                options.progress({
                  response: response,
                  counter: options.counter,
                  total_files: _this.files.length
                });
              }
              return _this.send(options);
            };
          })(this));
        }
      },
      _set_params: function(data, file, options) {
        data.append(options.name, file);
        if (options.params) {
          $.each(options.params, function(k, v) {
            return data.append(k, v);
          });
        }
        return data;
      },
      _post_data: function(data, options, callback) {
        return $.ajax({
          url: options.url,
          type: options.type,
          data: data,
          processData: false,
          contentType: false,
          success: callback
        });
      }
    });
    return $(document).ready(function() {
      return $.each($('input[type=file]'), function(i, element) {
        return $(element).sendFilesProxy();
      });
    });
  })(jQuery);

}).call(this);
